### PR TITLE
fix: restore monitoring dashboard rendering

### LINKED ISSUE #129: [Bug]: Monitoring dashboard template uses undefined div helper
## 🐛 Bug Description
The monitoring dashboard template uses a `div` helper to format memory values, but no template function named `div` is registered before parsing the template.

As a result, the monitoring dashboard route (`/`) fails at runtime when the template is parsed/rendered.

---

## 🔁 Steps to Reproduce

1. Start the project with monitoring enabled
2. Access the monitoring dashboard route (`/`)
3. The dashboard handler parses `dashboardTemplate`
4. Template parsing fails because `div` is not defined

Minimal repro of the same template behavior in Go:

```go
template.New("dashboard").Parse(`{{printf "%.2f" (div 10 2.0)}}`)
```
This returns:

```go
template: dashboard:1: function "div" not defined
```

Relevant code:

monitoring/web.go: handleDashboard() parses the template directly
monitoring/web.go: dashboardTemplate uses div for memory formatting

---

## ✅ Expected Behavior
The monitoring dashboard should render successfully and display memory usage values in MB.

---

## ❌ Actual Behavior
The dashboard template fails at runtime because it references an undefined template helper (div).

This breaks the HTML dashboard route even though other monitoring endpoints may still work.

---

## 🧪 Reproducibility
- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable to reproduce

---

## 📸 Screenshots / Logs
Verified with a minimal Go template repro matching the current code path.

### PR DESCRIPTION
**Pull request by cotishq**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation
- [ ] CI

## Mention the secrets provider 

N/A

## Description

This PR fixes the monitoring dashboard render failure on `/`.

The dashboard template uses a `div` helper to format memory values, but no template function was registered before parsing the template. Because of that, the HTML dashboard route was failing at runtime while other monitoring endpoints such as `/metrics`, `/health`, and `/api/metrics` continued to work.

This change registers the missing template helper and adds a regression test for the dashboard handler.

## Commands & Configuration to test

```bash
env GOCACHE=/tmp/go-build-cache go test ./monitoring

// For manual verification, I also ran the monitoring web interface locally and checked:

curl -i http://127.0.0.1:8080/
curl -i http://127.0.0.1:8080/metrics
curl -i http://127.0.0.1:8080/health
curl -i http://127.0.0.1:8080/api/metrics
```

## Screenshots & Logs

Before the fix:

Screenshot From 2026-04-12 00-06-07

 --- 
 
 After the fix:
 
Screenshot From 2026-04-13 18-25-15

## Related Tickets & Documents

- Related Issue #129 
- Closes #129

### CODE REVIEW

**Comment by cotishq** [comment]
@sanjay7178 after your approval for the pr in the discord, i have raised it, please review and tell what changes are required, ill be happy to resolve it too

File: monitoring/web.go
Comment (sanjay7178) [inline monitoring/web.go]:
```suggestion
            <h1>Vault Swarm Plugin Monitor</h1>
```

Comment (sanjay7178) [inline monitoring/web.go]:
```suggestion
                <h3>System Metrics</h3>
```

Comment (sanjay7178) [inline monitoring/web.go]:
```suggestion
                <h3>Secret Rotation</h3>
```

Comment (sanjay7178) [inline monitoring/web.go]:
```suggestion
                <h3>Uptime & Status</h3>
```

Comment (sanjay7178) [inline monitoring/web.go]:
```suggestion
                    <span class="metric-value">{{if .Health.ticker_healthy}}Healthy{{else}}Unhealthy{{end}}</span>
```

File: monitoring/web_test.go
Comment (sanjay7178) [inline monitoring/web_test.go:1]: can you rewrite using ginkgo ?

**Review by sanjay7178 — CHANGES_REQUESTED** [review]
Other than these changes all other looks good

I suggested to remove emoji's , bcz they weren't rendering in the UI

File: monitoring/web_test.go
Comment (cotishq) [reply monitoring/web_test.go:1]: i rewrote it using ginkgo and its working fine too, but the vet ci is failing as ginkgo and gomega depend on unmaintained packages, so should i fix that by adding a exceptions.yml in vet or let it as it is ?

File: monitoring/web_test.go [hunk 1]
```diff
@@ -3,32 +3,38 @@ package monitoring
...
+		monitor.SetRotationInterval(10 * time.Second)
+		web = NewWebInterface(monitor, 8080)
+	})
+
+	Describe("Dashboard Handler", func() {
+		It("should render HTML with correct status and content type", func() {
+			req := httptest.NewRequest(http.MethodGet, "/", nil)
+			rec := httptest.NewRecorder()
+
+			web.handleDashboard(rec, req)
```
Comment (atharvamhaske) [inline monitoring/web_test.go]: this line can be added inside `JustBeforeEach()` , this is provided by ginkgo itself.

File: monitoring/web_test.go
Comment (sanjay7178) [reply monitoring/web_test.go:1]: then just revert the changes

Comment (cotishq) [reply monitoring/web_test.go:1]: done, i reverted it back to previous test, i have removed the emojis only in this commit

**Review by sanjay7178 — APPROVED** [review]
lgtm
