### PR TITLE
fix: parallelize secret polling checks

### LINKED ISSUE #97: [Bug]: In driver.go checkForSecretChanges() is polling secrets in sequential order.
## 🐛 Bug Description 

Currently secrets are polled sequentially. 
---

## 🔁 Steps to Reproduce

2. Click on '...'
3. Run command '...'

---

## ✅ Expected Behavior

In `driver.go`, the function `checkForSecretChanges()` polls tracked secrets for updates.  
Currently, this process runs sequentially, checking secrets one by one.

This introduces unnecessary latency. For example:

- If 10 secrets exist
- Each provider check takes ~50ms

Then a single polling cycle takes **~500ms**. This can be improved by processing secrets **in parallel using goroutines with bounded concurrency**, reducing total polling latency while avoiding excessive API calls.
---

## ❌ Actual Behavior
Use goroutines and run in parallel to look for changes in secrets.

---

## 🧪 Reproducibility
- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable to reproduce

---

## 📸 Screenshots / Logs
If applicable, add screenshots, logs, or error output to help explain your problem.

<details>
<summary>Logs</summary>

```text
paste logs here

Open for your views on this?

### PR DESCRIPTION
**Pull request by atharvamhaske**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [x] Optimization
- [ ] Documentation
- [ ] CI

## Mention the secrets provider

All supported providers (`vault`, `aws`, `gcp`, `azure`, `openbao`)

## Description

Updated `checkForSecretChanges()` in `driver.go` to poll tracked secrets in parallel using goroutines with bounded concurrency (`maxConcurrentSecretChecks = 5`) instead of checking them sequentially. This reduces polling cycle latency while still limiting concurrent provider calls.

## Commands & Configuration to test

```bash
gofmt -w driver.go
GOCACHE=/tmp/swarm-external-secrets-gocache go test ./...
```

Configuration:
- `ENABLE_ROTATION=true`
- `ROTATION_INTERVAL=10s` or any desired polling interval

## Screenshots & Logs

N/A

## Related Tickets & Documents

- Closes #97

Opened after accidentally creating the first PR against my fork instead of the upstream repository.

### CODE REVIEW

**Review by sanjay7178 — CHANGES_REQUESTED** [review]

File: driver.go [hunk 1]
```diff
@@ -299,21 +299,38 @@ func (d *SecretsDriver) checkForSecretChanges() {
 
 	log.Printf("Checking %d tracked secrets for changes", len(secrets))
 
+	const maxConcurrentSecretChecks = 5
```
[the remark this answers is not in the document]
Comment (atharvamhaske) [reply driver.go]: this was just hardcoded number based on not to stress servers and max to poll no be 5

[the remark this answers is not in the document]
Comment (sanjay7178) [reply driver.go]: I mean we're using secret labels as number of secrets. 

Get the lenght from the docker go sdk 
https://pkg.go.dev/github.com/docker/docker/client#Client.SecretList

[the remark this answers is not in the document]
Comment (sanjay7178) [reply driver.go]: Also consider this , if the docker compose is updated with the secret labels , In some cases the number of secret labels would increase or decreases . So we need make some workaround for it as well .

But we'll make this as separate gh issue.

**Comment by atharvamhaske** [comment]
hey @sanjay7178 should i make LEFTHOOK=0 as lefthook is failing here?

**Comment by sanjay7178** [comment]
> hey @sanjay7178 should i make LEFTHOOK=0 as lefthook is failing here?

No need , but mt comments we'rent resolved yet .

File: driver.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (atharvamhaske) [reply driver.go]: @sanjay7178 what number can we use here ?

**Comment by sanjay7178** [comment]
I couldn't see any much changes in this PR

**Comment by atharvamhaske** [comment]
> I couldn't see any much changes in this PR

hey there is one missing approval of how can we set to use number according to number of request?this https://github.com/sugar-org/swarm-external-secrets/pull/106#discussion_r2952910872
 and one merge conflict

File: driver.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (sanjay7178) [reply driver.go]: In this discussion i've said , the channel length needs to be based on number of secrets made by user (needs to be checked via docker compose at runtime).

**Comment by sanjay7178** [comment]
> > I couldn't see any much changes in this PR
> 
> hey there is one missing approval of how can we set to use number according to number of request?this [#106 (comment)](https://github.com/sugar-org/swarm-external-secrets/pull/106#discussion_r2952910872) and one merge conflict

I couldn't get you what you mean by approval ?

**Comment by atharvamhaske** [comment]
> > > I couldn't see any much changes in this PR
> 
> > 
> 
> > hey there is one missing approval of how can we set to use number according to number of request?this [#106 (comment)](https://github.com/sugar-org/swarm-external-secrets/pull/106#discussion_r2952910872) and one merge conflict
> 
> 
> 
> I couldn't get you what you mean by approval ? 

I mean this https://github.com/sugar-org/swarm-external-secrets/pull/106#discussion_r2952913528

**Comment by sanjay7178** [comment]
yes the chan needs to be minimum of number of secret labels

**Comment by sanjay7178** [comment]
also add a TODO comment for future changes

**Comment by sanjay7178** [comment]
can you fix the conflicts please ?

**Comment by atharvamhaske** [comment]
i have resolved the conflicts
check it @sanjay7178

File: driver.go [hunk 2]
```diff
@@ -300,8 +300,10 @@ func (d *SecretsDriver) checkForSecretChanges() {
 	log.Printf("Checking %d tracked secrets for changes", len(secrets))
 
 	const maxConcurrentSecretChecks = 5
+	// TODO: Revisit this limit if secret-label fanout or provider latency changes.
+	concurrentSecretChecks := min(len(secrets), maxConcurrentSecretChecks)
```
Comment (sanjay7178) [inline driver.go]: what happens in the case for number of secrets > maxConcurrentSecretChecks ?

**Review by sanjay7178 — CHANGES_REQUESTED** [review]
also few CI builds and checks are failing

File: driver.go (hunk 2 above)
Comment (atharvamhaske) [reply driver.go]: When the number of secrets exceeds maxConcurrentSecretChecks, processing is throttled to a maximum of 5 concurrent operations.
The remaining secrets are processed in batches as execution slots become available. This ensures controlled concurrency and prevents excessive load.

So effectively:
- Up to 5 secrets are processed in parallel
- Remaining secrets are queued and processed incrementally

**Comment by atharvamhaske** [comment]
resolved that closure syntax issue

File: driver.go (hunk 2 above)
Comment (sanjay7178) [reply driver.go]: But 5 is not a estimated number to have . Our goal is to not throttle if the chan fills up due to fixed chan length .

Comment (sanjay7178) [reply driver.go]: can't we stick to this 
```suggestion
	concurrentSecretChecks := len(secrets) + 1
```
instead ?

Comment (atharvamhaske) [reply driver.go]: sure

Comment (atharvamhaske) [reply driver.go]: can you push that changes

**Comment by atharvamhaske** [comment]
is it ready to get merged @sanjay7178 ?

**Comment by sanjay7178** [comment]
can you fix CI checks ?

**Comment by atharvamhaske** [comment]
> can you fix CI checks ?

yep i have removed unused var which was making lefthook fail, lgtm !

**Review by sanjay7178 — APPROVED** [review]
lgtm
