### PR TITLE
fix: secret rotation prefix matching

### LINKED ISSUE #145: [Bug]: secret rotation may update unrelated Docker secrets with matching name prefixes
## 🐛 Bug Description
During secret rotation, `buildUpdatedSecretReferences` updates every Swarm service secret reference whose name equals the rotated secret’s original Docker name or starts with `<originalName>-.`
That prefix rule was likely added so services already pinned to a prior rotated name (e.g. `mysecret-<nanoseconds>`) get updated on the next rotation. It also matches any other secret that happens to share that prefix. For example, rotating a secret named `api` matches `api-prod`, because `api-prod` starts with `api-`. Those references are then rewritten to the new rotated secret name and ID, so a service can silently end up mounting the wrong credential.

Relevant code: https://github.com/sugar-org/swarm-external-secrets/blob/05f87ab57c3a63124d8ccabe9aded91bdab6ac7e/driver.go#L536

---

## 🔁 Steps to Reproduce

1. Create two Docker secrets: one named api (managed / rotated by this plugin) and a separate secret named api-prod (or any name where <rotatedBase>- is a prefix of the unrelated secret).
2. Attach both secrets to a Swarm service (different mount paths).
3. Trigger rotation for the base secret api (provider emits a new value so the plugin rotates and calls updateServicesSecretReference).
4. Inspect the service spec: the reference that pointed at api-prod may now point at the new rotated secret name/ID for api.

---

## ✅ Expected Behavior
Only references that correspond to the secret actually being rotated should be updated:
- The exact Docker secret name that was the “current” version for that logical secret, and/or
- Names that are verified to be prior versions created by this plugin for that same logical secret (e.g. tracked IDs, labels, or a strict naming scheme that cannot collide with unrelated secrets).

---

## ❌ Actual Behavior
Any service secret whose `SecretName` satisfies `strings.HasPrefix(name, oldSecretName+"-")` is treated as part of the rotation lineage and is replaced with the new rotated secret’s name and ID - even when that name belongs to a different, unrelated Docker secret.

---

## 🧪 Reproducibility
- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable to reproduce

---

## 📸 Screenshots / Logs
N/A

### PR DESCRIPTION
**Pull request by cotishq**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation
- [ ] CI

## Mention the secrets provider

All providers that support rotation. This fix is in the shared Docker Swarm secret rotation path, not in a provider-specific implementation. 

## Description

ixes a secret rotation bug where service secret references were updated when their Docker secret name either matched the rotated secret name exactly or started with `<secretName>-`.

That prefix match could rewrite unrelated secrets with similar names. For example, rotating `api` could also update a service reference to `api-prod`.

The rotation update logic now matches references by:
- the old Docker secret ID, when available
- the exact original Docker secret name

This preserves rotation for the intended secret, including already-rotated secret names when their Docker secret ID matches, while avoiding prefix collisions.

Added regression tests for:
- exact secret name updates
- rotated secret name updates by matching Docker secret ID
- unrelated prefix-matching secrets like `api-prod`
- empty old secret ID handling

## Commands & Configuration to test

```bash
GOCACHE=/tmp/swarm-external-secrets-go-build go test ./...
```

## Screenshots & Logs
N/A
## Related Tickets & Documents

- Related Issue #145 
- Closes #145

### CODE REVIEW

**Comment by cotishq** [comment]
@sanjay7178 can you please review it and tell me what changes it still requires ?

File: driver.go [hunk 1]
```diff
@@ -527,13 +528,19 @@ func (d *SecretsDriver) updateServicesSecretReference(oldSecretName, newSecretNa
...
 	newSecretID string,
 	updatedSecrets []*swarm.SecretReference,
 ) bool {
 	needsUpdate := false
 	for i, secretRef := range secretRefs {
-		if secretRef.SecretName == oldSecretName || strings.HasPrefix(secretRef.SecretName, oldSecretName+"-") {
+		if secretRef == nil {
+			updatedSecrets[i] = nil
+			continue
+		}
```
Comment (sanjay7178) [inline driver.go:540]: why we needed to update `updatedSecrets[i]` to nil ?

**Review by sanjay7178 — COMMENTED** [review]
Other than this , all other changes looks good

File: driver.go (hunk 1 above)
Comment (cotishq) [reply driver.go:540]: It was added as defensive handling for possible nil `*swarm.SecretReference` entries after adding the nil guard. But since `updatedSecrets` is already initialized with nil values, the assignment is redundant. I can remove it and keep only continue.

Comment (cotishq) [reply driver.go:540]: i have removed it, its looks good now

**Review by sanjay7178 — APPROVED** [review]
lgtm
